### ISSUE TITLE
Warning after build

### ISSUE THREAD

**Issue by DRCRecoveryData** [mat1jaczyyy/mf64-performance-cfw#1]
after build i got warnings:
![ảnh](https://github.com/mat1jaczyyy/mf64-performance-cfw/assets/85211068/4d03286a-5676-4c85-980c-a0f36ee3fc8c)

**Comment by conc1erge** [comment]
i'm sure mat is still working on it and definitely not meant to be built by others yet because things could break and YMMV, not sure how the roadmap is rn but i'm just keeping a close eye on the project.

as long as you have the *.hex file you should be able to flash it to the MF64, then again it could brick that's why i'm choosing not to do things with it

**Comment by mat1jaczyyy** [comment]
those warnings are whatever lol
this repo is currently very WIP and is a mix of mine and 2010 djtt code
